### ISSUE TITLE
Attempting to return expired items Issue

### ISSUE THREAD

**Issue by Nrc0611** [GC-spigot/AdvancedAuctionHouse#11]
Whenever I try to return expired items it spams the console with this error:

EDIT: this also happens whenever a player tries to buy a item, still takes their money but doesnt take the item out of the auction house or gives it to them.

`[19:49:19 ERROR]: Could not pass event InventoryClickEvent to AdvancedAuctionHouse v1.4.2
org.bukkit.event.EventException
       
Caused by: java.lang.StackOverflowError
        at gc.utils.AManager.giveItem(AManager.java:107) ~[?:?]
        at gc.utils.AManager.giveItem(AManager.java:107) ~[?:?]
        at gc.utils.AManager.giveItem(AManager.java:107) ~[?:?]
        at gc.utils.AManager.giveItem(AManager.java:107) ~[?:?]
        at gc.utils.AManager.giveItem(AManager.java:107) ~[?:?]
        at gc.utils.AManager.giveItem(AManager.java:107) ~[?:?]
        at gc.utils.AManager.giveItem(AManager.java:107) ~[?:?]
        at gc.utils.AManager.giveItem(AManager.java:107) ~[?:?]`

And it repeats that last message for around 200-300 lines and does not give back the item at all.

**Comment by GC-spigot** [comment]
Fixed
