### ISSUE TITLE
version 1.16.2

### ISSUE THREAD

**Issue by Trclu** [GC-spigot/AdvancedAuctionHouse#17]
`[22:21:24] [Server thread/INFO]: [AdvancedAuctionHouse] Enabling AdvancedAuctionHouse v1.4.6
[22:21:25] [Server thread/INFO]: [AdvancedAuctionHouse] You are using invalid version of Minecraft [v1_16_R2]! Disabling...
[22:21:25] [Server thread/INFO]: [AdvancedAuctionHouse] Disabling AdvancedAuctionHouse v1.4.6
[22:21:25] [Server thread/ERROR]: Error occurred while disabling AdvancedAuctionHouse v1.4.6 (Is it up to date?)
java.lang.NullPointerException: null
    at gc.aah.Core.onDisable(Core.java:175) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.16.2-SNAPSHOT.jar:git-Spigot-b5a13e6-ee7116b]
    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:376) ~[spigot-1.16.2-SNAPSHOT.jar:git-Spigot-b5a13e6-ee7116b]
    at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[spigot-1.16.2-SNAPSHOT.jar:git-Spigot-b5a13e6-ee7116b]
    at gc.aah.nbt.backend.utils.MinecraftVersion.getVersion(MinecraftVersion.java:56) ~[?:?]
    at gc.aah.utils.AManager.matchMaterial(AManager.java:331) ~[?:?]
    at gc.aah.utils.AManager.matchMaterial(AManager.java:327) ~[?:?]
    at gc.aah.utils.Materials.matchMaterial(Materials.java:16) ~[?:?]
    at gc.aah.objects.AuctionGroup.<init>(AuctionGroup.java:89) ~[?:?]
    at gc.aah.handlers.AuctionHandler.<init>(AuctionHandler.java:26) ~[?:?]
    at gc.aah.Core.sync(Core.java:151) ~[?:?]
    at gc.aah.Core.onEnable(Core.java:62) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.2-SNAPSHOT.jar:git-Spigot-b5a13e6-ee7116b]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.2-SNAPSHOT.jar:git-Spigot-b5a13e6-ee7116b]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.2-SNAPSHOT.jar:git-Spigot-b5a13e6-ee7116b]
    at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:492) ~[spigot-1.16.2-SNAPSHOT.jar:git-Spigot-b5a13e6-ee7116b]
    at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:406) ~[spigot-1.16.2-SNAPSHOT.jar:git-Spigot-b5a13e6-ee7116b]
    at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[spigot-1.16.2-SNAPSHOT.jar:git-Spigot-b5a13e6-ee7116b]
    at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:219) ~[spigot-1.16.2-SNAPSHOT.jar:git-Spigot-b5a13e6-ee7116b]
    at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[spigot-1.16.2-SNAPSHOT.jar:git-Spigot-b5a13e6-ee7116b]
    at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.2-SNAPSHOT.jar:git-Spigot-b5a13e6-ee7116b]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]`

**Comment by Trclu** [comment]
please updata
